string = (f"🟣 __Vote Bounty Info:__\n\nVote on the trackers below, and attach a screenshot with the name of the "
          f"tracker to instantly receive your reward.\n\n💸💸 Click any of the links below to get started! 💸💸\n\n["
          f"DexTools](https://www.dextools.io/app/en/solana/pair-explorer"
          f"/DDnvC5rvvZeJLuNKBF6xsdqHA6GPKbLxYq8z1bzaotUC?t=1712460479955) hit the 👍🏻 \\(100,000,000 mSatoshis\\) "
          f"\\(Vote one time\\)\n\n[Birdeye](https://birdeye.so/token/mBTCb8YxTdnp9GfUhz7v5qnNix7iFQCMDWKsUDNp3uJ"
          f"?chain=solana) hit the 👍🏻 \\(50,000,000 mSatoshis\\) \\(Once every 24hours\\)\n\n[DexScreener]("
          f"https://dexscreener.com/solana/ddnvc5rvvzejlunkbf6xsdqha6gpkblxyq8z1bzaotuc)  hit the 🚀 \\(25,000,"
          f"000 mSatoshis\\) \\(Vote every hour\\)\n\nReach X votes and get "
          f"listed:\n\n[GemsRadar](https://gemsradar.com/coins/mini-bitcoin) login and vote 🗳 🔥 \\(500,"
          f"000,000 mSatoshis\\) 🔥\n\n[CoinAlpha]("
          f"https://coinalpha.app/token/mBTCb8YxTdnp9GfUhz7v5qnNix7iFQCMDWKsUDNp3uJ)  login and vote 🗳 \\(5,000,"
          f"000 mSatoshis\\) \\(Available every 24hrs\\)\n\n[CoinCatapult]("
          f"https://coincatapult.com/coin/mini-bitcoin-mbtc) vote 🗳 \\(5,000,000 mSatoshis\\) \\(Available every "
          f"6hrs\\)\n\n[CoinDiscovery](https://coindiscovery.app/coin/mini-bitcoin#description) vote 🗳 \\(5,000,"
          f"000 mSatoshis\\) \\(Available every hour\\)\n\n*Other Trackers:*\n[NTM.ai]("
          f"https://ntm.ai/token/mBTCb8YxTdnp9GfUhz7v5qnNix7iFQCMDWKsUDNp3uJ?graph"
          f"=DDnvC5rvvZeJLuNKBF6xsdqHA6GPKbLxYq8z1bzaotUC) vote 'Bullish' or 'Safu' \\(500,000 mSatoshis\\) \\("
          f"Available"
          f"every hour\\)\n[CoinBazooka](https://coinbazooka.com/coin/mini-bitcoin) vote 🗳 \\(250000 mSatoshis\\) \\("
          f"Available every 24hrs\\)\n[CoinScope](https://www.coinscope.co/coin/1-mbtc) login and vote 🗳 \\(250000 "
          f"mSatoshis\\) \\(Available every 24hrs\\)\n[CoinSniper](https://coinsniper.net/coin/63289) login and vote "
          f"🗳 \\(250000 mSatoshis\\) \\(Available every 24hrs\\)\n[top100token]("
          f"https://top100token.com/address/mBTCb8YxTdnp9GfUhz7v5qnNix7iFQCMDWKsUDNp3uJ) vote 🚀 \\(250000 "
          f"mSatoshis\\) \\("
          f"Available every 24hrs\\)\n[Rugfreecoins](https://www.rugfreecoins.com/coin-details/24899) vote 🔥 \\("
          f"150000 mSatoshis\\) \\(Available every 24hrs\\)\n[CNToken.io](https://cncrypto.io/coin/mini-bitcoin) vote "
          f"🗳 \\(150000 mSatoshis\\) \\(Available every 24hrs\\)\n[CoinMonHunt](https://coinmoonhunt.com/coin/Mini "
          f"Bitcoin)  vote 🗳 \\(150000 mSatoshis\\) \\(Available every hour\\)\n[CoinBoom]("
          f"https://coinboom.net/coin/mini-bitcoin-2) vote 🚀\\(30000 mSatoshis\\) \\(Available every 24hrs\\)\n["
          f"CoinMooner](https://coinboom.net/coin/mini-bitcoin-2)  vote 🚀\\(30000 mSatoshis\\) \\(Available every "
          f"24hrs\\)\n[CoinVote](https://coinvote.cc/en/coin/Mini-Bitcoin)  login and hit the 👍🏻 \\(30000 "
          f"mSatoshis\\) \\(Available every 24hrs\\)")