#new refined handler

import time

#users will place a game order with a epoch value,each second will be 0.125x multiplier move

multiplier_step_per_second = 0.125

active_games = {}


#also add dtatbase for all the games the users played and a log file?

def place_game_order(username, bet_size):
    current_time_stamp = time.time()
    max_multiplier = 40  # this will be obviously generated by the crash algorithm
    if username not in active_games:
        active_games[username] = [current_time_stamp, max_multiplier, bet_size]
        return True
    else:
        return False  #meaingin the already are in a game atm


def cashout_event(username):
    time_stamp = time.time()
    if username in active_games:
        data_list = active_games[username]
        time_interval = time_stamp - data_list[0]
        max_interval = data_list[1] / multiplier_step_per_second
        if time_interval <= max_interval:
            return multiplier_step_per_second * time_interval

        else:
            return 0
        #rmove the from active plpayers queue as they cashed out in time

    else:
        return -1
